####################### Configuration ######################

ENABLE_NETWORK_STATS="yes" ## Enable or disable network statistics generation using vnStat
INTERFACE="<YOUR_INTERFACE>" ## Network interface to monitor (e.g., eth0, wlan0)

PAGE_TITLE="Network Traffic and Chrony Statistics for ${INTERFACE}"
OUTPUT_DIR="/var/www/html/chrony-network-stats" ## Output directory for HTML and images
HTML_FILENAME="index.html" ## Output HTML file name

RRD_DIR="/var/lib/chrony-rrd"
RRD_FILE="$RRD_DIR/chrony.rrd" ## RRD file for storing chrony statistics

ENABLE_LOGGING="no" ## Enable or disable logging to a file
LOG_FILE="/var/log/chrony-network-stats.log"

AUTO_REFRESH_SECONDS=0 ## Auto-refresh interval in seconds (0 = disabled, e.g., 300 for 5 minutes)
GITHUB_REPO_LINK_SHOW="yes" ## You can display the link to the repo 'chrony-stats' in the HTML footer | Not required | Default: no


###### Graph regeneration intervals (in seconds) ######## 

# GRAPH_REGEN_DAY=     ## Day graphs are always regenerated unless is uncommented
GRAPH_REGEN_WEEK=3600    ## 1 hour
GRAPH_REGEN_MONTH=21600  ## 6 hours
GRAPH_REGEN_YEAR=86400   ## 24 hours

GRAPH_REGEN_NETWORK=3600 ## 1 hour (vnStat images)

################ Advanced Configuration ################

TIMEOUT_SECONDS=5
SERVER_STATS_UPPER_LIMIT=70000 ## When chrony restarts, it generate abnormally high values (e.g., 12M) | This filters out values above the threshold
CHRONY_ALLOW_DNS_LOOKUP="no" ## Disabled by default to avoid DNS lookups. Set to "yes" for more readable output (hostnames instead of IPs)

DISPLAY_PRESET="default" ## Preset for large screens. Options: default | 2k | 4k
WIDTH=800   ## These graph sizes are changing with DISPLAY_PRESET
HEIGHT=300  ##